### ISSUE TITLE
Bad Practice to Query DB from the View

### ISSUE THREAD

**Issue by alexgriff** [learn-co-curriculum/partial-locals-reading#10] opened 2016-08-24 17:47 UTC
The README instructs students to remove the `@author` instance variable from the controller and only pass `@post` to the view because in the view you can say `@post.author`.  The `#author` method when called on `@post` actually makes a call to the database, it runs some SQL.  It is generally bad practice to make db queries from the view, exactly what the README says is better practice here.

> In fact, with locals, we can eliminate @author = @post.author line in the posts#show action in the controller completely, by instead only accessing that data in where we need it, in the partial.
> 
> Let's remove that line of code in our controller, and in the view pass through the author information by changing our code to the following:

``` ruby
app/controllers/posts_controller

def show
    @post = Post.find(params[:id])
  end
app/views/posts/show.html.erb

Information About the Post
<%= render partial: "authors/author", locals: {post_author: @post.author} %>
<%= @post.title %>
<%= @post.content %>
```

> This code is much better. We are being more explicit about our dependencies, reducing lines of code in our codebase, and reducing the scope of the author variable

**Comment by maxwellbenton** [comment] 2018-08-28 15:22
Hi @alexgriff,

Looks like this change was implemented so I am going to close this issue.

Thanks for being awesome!

**Closed by maxwellbenton** 2018-08-28 15:22 UTC
Labels: Curriculum

**Comment by Sdcrouse** [comment] 2019-12-24 01:27
I think this needs to be reopened; the problem is still there.
